---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - multitenancy.istio.eoinfennessy.com
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multitenancy.istio.eoinfennessy.com
  resources:
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - multitenancy.istio.eoinfennessy.com
  resources:
  - zones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.istio.io
  resources:
  - sidecars
  verbs:
  - '*'
- apiGroups:
  - security.istio.io
  resources:
  - authorizationPolicies
  verbs:
  - '*'
