# permissions for end users to edit zones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: istio-zones
    app.kubernetes.io/managed-by: kustomize
  name: zone-editor-role
rules:
- apiGroups:
  - configscoping.istio.eoinfennessy.com
  resources:
  - zones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - configscoping.istio.eoinfennessy.com
  resources:
  - zones/status
  verbs:
  - get
