apiVersion: v1
kind: Service
metadata:
  name: httpbin-1-blue-a
  namespace: blue-a
spec:
  selector:
    app: httpbin-1-blue-a
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-2-blue-a
  namespace: blue-a
spec:
  selector:
    app: httpbin-2-blue-a
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-1-blue-b
  namespace: blue-b
spec:
  selector:
    app: httpbin-1-blue-b
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-2-blue-b
  namespace: blue-b
spec:
  selector:
    app: httpbin-2-blue-b
  ports:
    - port: 80
      targetPort: 8080
  